name: Build for Architect Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      uses: ./.github/Action
      #run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish 
    - name: Upload Coding Dojos Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CodingDojos
        path: /home/runner/work/GitHubSessions/GitHubSessions/GitHubsessions/bin/Debug/net5.0/publish/
    - name: Test
      run: dotnet test --no-build --verbosity normal
#deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'Production'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#    steps:
#      - name: Download artifact from build job
#        uses: actions/download-artifact@v2
#        with:
#          name: php-app

#      - name: 'Deploy to Azure Web App'
#        uses: azure/webapps-deploy@v2
#        id: deploy-to-webapp
#        with:
#          app-name: 'DevOpsMaturityAssessment'
#          slot-name: 'Production'
#          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_68271DA2278B49DBB75EF052259FC6F9 }}
#          package: .
